layer_json = {
    "id": 50787,
    "url": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/",
    "type": "layer",
    "title": "NZ Geodetic Marks",
    "first_published_at": "2011-05-22T06:05:15.135161Z",
    "thumbnail_url": "https://tiles-cdn.koordinates.com/services/tiles/v4/thumbnail/layer=50787.422069,style=2088.1516910372/1200x630.png",
    "published_at": "2025-05-16T23:31:49.272694Z",
    "featured_at": None,
    "services": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/services/",
    "user_capabilities": [
        "can-star",
        "can-export",
        "can-spatial-query",
        "can-view-data-table",
    ],
    "user_permissions": ["find", "view", "download"],
    "description": "This dataset provides information about the position, position accuracy, mark name, mark type, condition and unique four letter code for geodetic marks in terms of a New Zealand's official geodetic datum.\n\nThe dataset only contains marks that are within the New Zealand mainland and offshore islands. These positions have been generated using geodetic observations such as precise differential GPS or electronic distance and theodolite angles measurements. The positions are either 2D or 3D depending of the availability of this measurement data.\n\nThe source data is from Toitū Te Whenua Land Information New Zealand's (LINZ) Landonline system where it is used by Land Surveyors. This dataset is updated daily to reflect changes made in the Landonline.\n\n\nAccuracy\n============\nGeodetic marks with a coordinate order of 5 or less have been positioned in terms of NZGD2000. Lower order marks (order 6 and greater) are derived from cadastral surveys, lower accuracy measurement techniques or inaccurate historical datum transformations, and may be significantly less accurate.\n\nThe accuracy of NZGD2000 coordinates is described by a series of 'orders' classifications. Positions in terms of NZGD2000 are described by three-dimensional coordinates (latitude, longitude, ellipsoidal height). The accuracy of a survey mark is indicated by its Order. Orders are classifications based on the quality of the coordinate in relation to the datum and in relation to other surrounding marks. For more information [see](https://www.linz.govt.nz/guidance/geodetic-system/coordinate-systems-used-new-zealand/coordinate-and-height-accuracy/coordinate-orders)\n\nNote that the accuracy applies at the time the mark was last surveyed. Refer to the web geodetic database for historical information about mark coordinates.\n\nNote also that the existence of a mark in this dataset does not imply that there is currently a physical mark in the ground - the dataset includes destroyed or lost historical marks. The geodetic database provides more information on the mark status, valid at last time it was visited by LINZ or a maintenance contractor.",
    "description_html": "<p>This dataset provides information about the position, position accuracy, mark name, mark type, condition and unique four letter code for geodetic marks in terms of a New Zealand's official geodetic datum.</p>\n<p>The dataset only contains marks that are within the New Zealand mainland and offshore islands. These positions have been generated using geodetic observations such as precise differential GPS or electronic distance and theodolite angles measurements. The positions are either 2D or 3D depending of the availability of this measurement data.</p>\n<p>The source data is from Toitū Te Whenua Land Information New Zealand's (LINZ) Landonline system where it is used by Land Surveyors. This dataset is updated daily to reflect changes made in the Landonline.</p>\n<h4>Accuracy</h4>\n<p>Geodetic marks with a coordinate order of 5 or less have been positioned in terms of NZGD2000. Lower order marks (order 6 and greater) are derived from cadastral surveys, lower accuracy measurement techniques or inaccurate historical datum transformations, and may be significantly less accurate.</p>\n<p>The accuracy of NZGD2000 coordinates is described by a series of 'orders' classifications. Positions in terms of NZGD2000 are described by three-dimensional coordinates (latitude, longitude, ellipsoidal height). The accuracy of a survey mark is indicated by its Order. Orders are classifications based on the quality of the coordinate in relation to the datum and in relation to other surrounding marks. For more information <a href=\"https://www.linz.govt.nz/guidance/geodetic-system/coordinate-systems-used-new-zealand/coordinate-and-height-accuracy/coordinate-orders\">see</a></p>\n<p>Note that the accuracy applies at the time the mark was last surveyed. Refer to the web geodetic database for historical information about mark coordinates.</p>\n<p>Note also that the existence of a mark in this dataset does not imply that there is currently a physical mark in the ground - the dataset includes destroyed or lost historical marks. The geodetic database provides more information on the mark status, valid at last time it was visited by LINZ or a maintenance contractor.</p>",
    "group": {
        "id": 2004,
        "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2004/",
        "name": "National Geodetic Office",
        "country": "NZ",
        "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
        "type": "normal",
    },
    "publisher": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
    "data": {
        "storage": "classic",
        "datasources": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/datasources/",
        "fields": [
            {"name": "id", "type": "integer"},
            {"name": "geodetic_code", "type": "string"},
            {"name": "current_mark_name", "type": "string"},
            {"name": "description", "type": "string"},
            {"name": "mark_type", "type": "string"},
            {"name": "beacon_type", "type": "string"},
            {"name": "mark_condition", "type": "string"},
            {"name": "order", "type": "integer"},
            {"name": "land_district", "type": "string"},
            {"name": "latitude", "type": "numeric"},
            {"name": "longitude", "type": "numeric"},
            {"name": "ellipsoidal_height", "type": "numeric"},
            {"name": "shape", "type": "geometry"},
        ],
        "encoding": None,
        "crs": {
            "id": "EPSG:4167",
            "url": "https://data.linz.govt.nz/services/api/v1.x/coordinate-systems/EPSG:4167/",
            "name": "NZGD2000",
            "kind": "geographic 2D",
            "unit_horizontal": "degree",
            "unit_vertical": "",
            "url_external": "https://epsg.io/4167",
            "component_horizontal": None,
            "component_vertical": None,
            "srid": 4167,
        },
        "primary_key_fields": ["id"],
        "geometry_field": "shape",
        "geometry_type": "point",
        "source_revision": 5811,
        "omitted_fields": [],
        "tile_revision": 422069,
        "feature_count": 132966,
        "extent": {
            "type": "Polygon",
            "coordinates": [
                [
                    [165.79999990000002, -52.5550811],
                    [165.79999990000002, -29.038753920889707],
                    [183.9000001, -29.038753920889707],
                    [183.9000001, -52.5550811],
                    [165.79999990000002, -52.5550811],
                ]
            ],
        },
        "datasource_count": 1,
        "change_summary": {
            "inserted": 1,
            "updated": 227,
            "deleted": 0,
            "schema_changes": {
                "added": [],
                "changed": [],
                "removed": [],
                "srid_changed": False,
                "geometry_type_changed": False,
                "primary_keys_changed": False,
            },
        },
        "source_summary": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/data/source-summary/",
        "import_started_at": "2025-05-16T15:47:55.320352Z",
        "import_ended_at": "2025-05-16T15:48:16.105920Z",
        "import_log": {
            "invalid_geometries": 0,
            "messages": 0,
            "url": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/data/import-log/",
        },
        "import_version": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/",
        "update_available": False,
        "sample": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/data/sample/",
        "raster_resolution": None,
        "empty_geometry_count": 0,
        "has_z": False,
        "export_formats": [
            {"name": "Shapefile", "mimetype": "application/x-zipped-shp"},
            {"name": "MapInfo TAB", "mimetype": "application/x-ogc-mapinfo_file"},
            {"name": "MapInfo MIF", "mimetype": "application/x-ogc-mapinfo_file+mif"},
            {"name": "CSV", "mimetype": "text/csv"},
            {"name": "GeoPackage / SQLite", "mimetype": "application/x-ogc-gpkg"},
            {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
            {"name": "KML", "mimetype": "application/vnd.google-earth.kml+xml"},
            {"name": "DWG", "mimetype": "image/vnd.dwg"},
            {"name": "PDF", "mimetype": "application/pdf"},
        ],
    },
    "url_html": "https://data.linz.govt.nz/layer/50787-nz-geodetic-marks/",
    "url_canonical": "https://data.linz.govt.nz/layer/50787-nz-geodetic-marks/",
    "published_version": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/",
    "this_version": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/",
    "kind": "vector",
    "categories": [
        {
            "name": "Geodetic",
            "slug": "geodetic",
            "key": "geodetic",
            "url": "https://data.linz.govt.nz/services/api/v1.x/categories/geodetic/",
            "ancestors": [],
        }
    ],
    "tags": ["New Zealand"],
    "collected_at": None,
    "created_at": "2011-05-22T06:05:15.135161Z",
    "license": {
        "id": 171,
        "title": "Creative Commons Attribution 4.0 International",
        "type": "cc-by",
        "jurisdiction": "",
        "version": "4.0",
        "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
        "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
        "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
    },
    "metadata": {
        "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/251238/metadata-resources/20289/",
        "native": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/metadata/",
        "iso": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/metadata/iso/",
        "dc": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/metadata/dc/",
    },
    "elevation_field": "",
    "styles": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/styles/",
    "default_style": {"id": 2088},
    "attachments": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/attachments/",
    "settings": {
        "is_pinned": None,
        "feedback_enabled": True,
        "is_source_mirror": False,
    },
    "repository": {
        "id": "p3VoJ0x",
        "full_name": "linz/nz-geodetic-marks",
        "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/nz-geodetic-marks/",
        "clone_location_ssh": "kart@data.koordinates.com:linz/nz-geodetic-marks",
        "clone_location_https": "https://data.koordinates.com/linz/nz-geodetic-marks",
        "type": "repo",
        "title": "NZ Geodetic Marks",
        "first_published_at": "2023-08-08T23:48:04.539479Z",
        "published_at": None,
        "settings": {"feedback_enabled": True},
        "user_capabilities": ["can-star", "can-clone"],
        "user_permissions": ["find", "view", "download"],
    },
    "geotags": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/geotags/",
    "num_views": 49511,
    "num_downloads": 7967,
    "is_starred": False,
    "public_access": "download",
    "version": {
        "id": 413912,
        "url": "https://data.linz.govt.nz/services/api/v1.x/layers/50787/versions/413912/",
        "status": "ok",
        "created_at": "2025-05-16T15:03:54.867962Z",
        "reference": "",
        "progress": 1.0,
        "data_import": True,
    },
}

table_json = {
    "id": 113761,
    "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/",
    "type": "table",
    "title": "Suburb Locality - Population",
    "first_published_at": "2023-06-16T03:27:20.121434Z",
    "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/113761/422171/og.png",
    "published_at": "2025-05-19T23:31:26.869122Z",
    "featured_at": None,
    "services": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/",
    "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
    "user_permissions": ["find", "view", "download"],
    "description": "The Population data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). This table contains the population estimate for each suburb and locality, provided by StatsNZ.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
    "description_html": '<p>The Population data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. This table contains the population estimate for each suburb and locality, provided by StatsNZ.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
    "group": {
        "id": 2174,
        "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
        "name": "Addressing",
        "country": "NZ",
        "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
        "type": "normal",
    },
    "publisher": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
    "data": {
        "storage": "classic",
        "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/datasources/",
        "fields": [
            {"name": "id", "type": "integer"},
            {"name": "suburb_locality_id", "type": "integer"},
            {"name": "population_estimate", "type": "integer"},
        ],
        "encoding": "utf-8",
        "crs": None,
        "primary_key_fields": ["id"],
        "geometry_field": None,
        "geometry_type": "",
        "omitted_fields": [],
        "tile_revision": 422171,
        "feature_count": 3190,
        "extent": None,
        "datasource_count": 1,
        "change_summary": {
            "inserted": 0,
            "updated": 0,
            "deleted": 0,
            "schema_changes": {
                "added": [],
                "changed": [],
                "removed": [],
                "srid_changed": False,
                "geometry_type_changed": False,
                "primary_keys_changed": False,
            },
        },
        "source_summary": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/source-summary/",
        "import_started_at": "2025-05-19T23:30:16.526945Z",
        "import_ended_at": "2025-05-19T23:30:23.368693Z",
        "import_log": {
            "invalid_geometries": 0,
            "messages": 0,
            "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/import-log/",
        },
        "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
        "update_available": False,
        "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/sample/",
        "raster_resolution": None,
        "empty_geometry_count": 3190,
        "has_z": False,
        "export_formats": [
            {"name": "DBF (dBase III)", "mimetype": "application/x-zipped-shp"},
            {"name": "MapInfo TAB", "mimetype": "application/x-ogc-mapinfo_file"},
            {"name": "MapInfo MIF", "mimetype": "application/x-ogc-mapinfo_file+mif"},
            {"name": "CSV", "mimetype": "text/csv"},
            {"name": "GeoPackage / SQLite", "mimetype": "application/x-ogc-gpkg"},
            {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
        ],
    },
    "url_html": "https://data.linz.govt.nz/table/113761-suburb-locality-population/",
    "url_canonical": "https://data.linz.govt.nz/table/113761-suburb-locality-population/",
    "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
    "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
    "kind": "table",
    "categories": [
        {
            "name": "Suburbs and Localities",
            "slug": "suburbs-and-localities",
            "key": "suburbs-and-localities",
            "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
            "ancestors": [],
        }
    ],
    "tags": ["New Zealand"],
    "collected_at": None,
    "created_at": "2023-06-16T03:25:23.567953Z",
    "license": {
        "id": 171,
        "title": "Creative Commons Attribution 4.0 International",
        "type": "cc-by",
        "jurisdiction": "",
        "version": "4.0",
        "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
        "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
        "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
    },
    "metadata": {
        "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253860/metadata-resources/22221/",
        "native": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/",
        "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/iso/",
        "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/dc/",
    },
    "elevation_field": "",
    "attachments": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/attachments/",
    "settings": {
        "is_pinned": None,
        "feedback_enabled": True,
        "is_source_mirror": False,
    },
    "repository": {
        "id": "Y3N4Bwq",
        "full_name": "linz/suburb-locality-population",
        "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-population/",
        "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-population",
        "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-population",
        "type": "repo",
        "title": "Suburb Locality - Population",
        "first_published_at": "2023-08-08T19:30:25.028943Z",
        "published_at": None,
        "settings": {"feedback_enabled": True},
        "user_capabilities": ["can-star", "can-clone"],
        "user_permissions": ["find", "view", "download"],
    },
    "geotags": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/geotags/",
    "num_views": 3008,
    "num_downloads": 532,
    "is_starred": False,
    "public_access": "download",
    "version": {
        "id": 414039,
        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
        "status": "ok",
        "created_at": "2025-05-19T23:30:04.023695Z",
        "reference": "",
        "progress": 1.0,
        "data_import": True,
    },
}
