document = {
    request: "https://data.linz.govt.nz/services/api/v1.x/documents/12628/",
    response: {
        "id": 12628,
        "title": "NZ Roads Data Dictionary",
        "url": "https://data.linz.govt.nz/services/api/v1.x/documents/12628/",
        "type": "document",
        "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/documents/12628/12871/thumb-1200x630.png",
        "first_published_at": "2016-04-14T02:34:14.519414Z",
        "published_at": "2016-11-21T20:50:09.834558Z",
        "user_capabilities": ["can-star", "can-export"],
        "group": {
            "id": 2174,
            "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
            "name": "Addressing",
            "country": "NZ",
            "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
            "type": "normal",
        },
        "url_html": "https://data.linz.govt.nz/document/12628-nz-roads-data-dictionary/",
        "url_download": "https://data.linz.govt.nz/services/api/v1.x/documents/12628/versions/12871/download/",
        "extension": "pdf",
        "file_size": 720006,
        "file_size_formatted": "720 KB",
        "featured_at": null,
        "user_permissions": ["find", "view", "download"],
        "description": "This document provides detailed metadata (data dictionary) for the new simplified NZ Roads and comprehensive NZ Roads datasets published on the LINZ Data Service. These datasets contain a new structure for the road data that we currently hold as part of our address information, kept for electoral purposes.",
        "description_html": "<p>This document provides detailed metadata (data dictionary) for the new simplified NZ Roads and comprehensive NZ Roads datasets published on the LINZ Data Service. These datasets contain a new structure for the road data that we currently hold as part of our address information, kept for electoral purposes.</p>",
        "publisher": {
            "id": "data.linz.govt.nz",
            "name": "Land Information New Zealand",
            "html_url": "https://data.linz.govt.nz/",
            "slug_for_url": null,
            "theme": {
                "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                "background_color": "004964",
            },
            "site": {"url": "https://data.linz.govt.nz", "name": "LINZ Data Service"},
            "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
            "flags": {},
            "description": null,
        },
        "published_version": "https://data.linz.govt.nz/services/api/v1.x/documents/12628/versions/12871/",
        "latest_version": "https://data.linz.govt.nz/services/api/v1.x/documents/12628/versions/21530/",
        "this_version": "https://data.linz.govt.nz/services/api/v1.x/documents/12628/versions/12871/",
        "data": {"datasource": null},
        "categories": [
            {
                "name": "Full Roads (Addressing)",
                "slug": "full-roads-addressing",
                "key": "roads-and-addresses/full-roads-addressing",
                "url": "https://data.linz.govt.nz/services/api/v1.x/categories/roads-and-addresses/full-roads-addressing/",
                "ancestors": [
                    {
                        "name": "Roads and Addresses",
                        "slug": "roads-and-addresses",
                        "key": "roads-and-addresses",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/roads-and-addresses/",
                    }
                ],
            }
        ],
        "tags": [],
        "license": {
            "id": 171,
            "title": "Creative Commons Attribution 4.0 International",
            "type": "cc-by",
            "jurisdiction": "",
            "version": "4.0",
            "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
            "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
            "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
        },
        "metadata": null,
        "attached": "https://data.linz.govt.nz/services/api/v1.x/documents/12628/attached/",
        "settings": {"feedback_enabled": true},
        "num_views": 8754,
        "num_downloads": 1646,
        "url_canonical": "https://data.linz.govt.nz/document/12628-nz-roads-data-dictionary/",
        "is_starred": false,
        "version": {
            "id": 12871,
            "url": "https://data.linz.govt.nz/services/api/v1.x/documents/12628/versions/12871/",
            "created_at": "2016-11-21T20:50:01.022820Z",
            "created_by": {
                "id": 44101,
                "url": "https://data.linz.govt.nz/services/api/v1.x/users/44101/",
                "first_name": "Daniel",
                "last_name": "Silk",
                "country": "NZ",
                "geotag": "global/oceania/new-zealand",
            },
        },
        "public_access": "download",
    },
}
