response = {
    "id": 50804,
    "url": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/",
    "type": "layer",
    "title": "NZ Property Titles",
    "first_published_at": "2011-05-31T06:53:10.949836Z",
    "thumbnail_url": "https://tiles-cdn.koordinates.com/services/tiles/v4/thumbnail/layer=50804.422056,style=auto/1200x630.png",
    "published_at": "2025-05-16T22:27:46.308908Z",
    "featured_at": null,
    "services": [
        {
            "id": "s3TxkM77wmK4dZt",
            "authority": "ogc",
            "key": "csw",
            "short_name": "CS-W",
            "label": "Catalog Service for the Web",
            "auth_method": [],
            "auth_scopes": [],
            "domain": "data.linz.govt.nz",
            "template_urls": [
                {
                    "name": "Web Catalog Services",
                    "service_url": "https://data.linz.govt.nz/services/csw/?service=CSW&amp;request=GetCapabilities",
                }
            ],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3TxkM77wmK4dZt/permissions/",
            "advertised": true,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3TxkM77wmLypzp",
            "authority": "kart",
            "key": "kart",
            "short_name": "Kart",
            "label": "Kart Repository",
            "auth_method": [],
            "auth_scopes": [],
            "domain": "data.linz.govt.nz",
            "template_urls": [
                {
                    "name": "SSH Clone Location",
                    "service_url": "kart@data.koordinates.com:linz/nz-property-titles",
                },
                {
                    "name": "HTTPS Clone Location",
                    "service_url": "https://data.koordinates.com/linz/nz-property-titles",
                },
            ],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3TxkM77wmLypzp/permissions/",
            "advertised": true,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3TxkM77wmMBqG3",
            "authority": "ogc",
            "key": "wfs",
            "short_name": "WFS",
            "label": "OGC Web Feature Service",
            "auth_method": ["apikey"],
            "auth_scopes": ["wxs:wfs"],
            "domain": "data.linz.govt.nz",
            "template_urls": [
                {
                    "name": "Layer WFS Capabilities",
                    "service_url": "https://data.linz.govt.nz/services;key=[api_token]/wfs/layer-50804/?service=WFS&request=GetCapabilities",
                },
                {
                    "name": "All WFS Capabilities",
                    "service_url": "https://data.linz.govt.nz/services;key=[api_token]/wfs/?service=WFS&request=GetCapabilities",
                },
            ],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3TxkM77wmMBqG3/permissions/",
            "advertised": true,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3TxkM77wmRRZqC",
            "authority": "koordinates",
            "key": "wfs-changesets",
            "short_name": "WFS Changesets",
            "label": "Retrieve data changesets via WFS",
            "auth_method": ["apikey"],
            "auth_scopes": ["wxs:wfs"],
            "domain": "data.linz.govt.nz",
            "template_urls": [
                {
                    "name": "WFS Changesets",
                    "service_url": "https://data.linz.govt.nz/services;key=[api_token]/wfs/layer-50804?service=WFS&version=2.0.0&request=GetFeature&TypeName=layer-50804-changeset&OutputFormat=[output_format]&sortBy=[sort_by]&viewparams=from:[start_time];to:[end_time]",
                }
            ],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3TxkM77wmRRZqC/permissions/",
            "advertised": true,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3TxkM77wmRgx9x",
            "authority": "koordinates",
            "key": "spatial-query-vector",
            "short_name": "Spatial Query API",
            "label": "Simple latitude, longitude spatial queries",
            "auth_method": ["apikey"],
            "auth_scopes": ["query"],
            "domain": "data.linz.govt.nz",
            "template_urls": [
                {
                    "name": "Vector JSON Query",
                    "service_url": "https://data.linz.govt.nz/services/query/v1/vector.json?key=[api_token]&layer=50804&x=[x]&y=[y]&max_results=3&radius=10000&geometry=true&with_field_names=true",
                },
                {
                    "name": "Vector XML Query",
                    "service_url": "https://data.linz.govt.nz/services/query/v1/vector.xml?key=[api_token]&layer=50804&x=[x]&y=[y]&max_results=3&radius=10000&geometry=true&with_field_names=true",
                },
            ],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3TxkM77wmRgx9x/permissions/",
            "advertised": true,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3VH216XSCb2Q9L",
            "authority": "koordinates",
            "key": "spatial-query-ui",
            "short_name": "Spatial Query UI",
            "auth_method": [],
            "auth_scopes": [],
            "domain": "data.linz.govt.nz",
            "template_urls": [],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3VH216XSCb2Q9L/permissions/",
            "advertised": false,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3VH216XSCXGKpD",
            "authority": "koordinates",
            "key": "data-table",
            "short_name": "Data Table API",
            "label": "Data table API for feature and raster-tile queries",
            "auth_method": ["apikey"],
            "auth_scopes": ["query"],
            "domain": "data.linz.govt.nz",
            "template_urls": [],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3VH216XSCXGKpD/permissions/",
            "advertised": false,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3VH216XSCYnKPL",
            "authority": "koordinates",
            "key": "data-table-ui",
            "short_name": "Data Table UI",
            "auth_method": [],
            "auth_scopes": [],
            "domain": "data.linz.govt.nz",
            "template_urls": [],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3VH216XSCYnKPL/permissions/",
            "advertised": false,
            "user_capabilities": [],
            "enabled": true,
        },
        {
            "id": "s3VH216XSCXwh7Q",
            "authority": "koordinates",
            "key": "export",
            "short_name": "Export",
            "label": "Export Service",
            "auth_method": [],
            "auth_scopes": [],
            "domain": "data.linz.govt.nz",
            "template_urls": [],
            "capabilities": [],
            "permissions": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/services/s3VH216XSCXwh7Q/permissions/",
            "advertised": false,
            "user_capabilities": [],
            "enabled": true,
        },
    ],
    "user_capabilities": [
        "can-star",
        "can-export",
        "can-spatial-query",
        "can-view-data-table",
    ],
    "user_permissions": ["find", "view", "download"],
    "description": "This dataset provides title information (excluding ownership) where there is a relationship to one or more primary parcels.\n\nA Record of Title is a record of a property's owners, legal description and the rights and responsibilities  registered against the title.This dataset does not contain any ownership information so that it can be freely distributed. If ownership information is required, you need to [apply for access](https://www.linz.govt.nz/products-services/data/licensing-and-using-data/linz-licence-personal-data).\n\nThere can be multiple parcels associated with a title, and a title may only have a part share in a parcel. This means the shape representing the title will be an aggregation of all parcels that the title is associated with. The ‘spatial extents shared’ attribute when equal to ‘false’ will indicate that title has exclusive interest over all of the shape (this will be case for the vast majority).\n\nThe originating data for parcel/title associations includes some non-official sources where the official data does not support a link. For more information see the [LINZ website](https://www.linz.govt.nz/products-services/data/types-linz-data/property-ownership-and-boundary-data/types-lds-property-ownership-and-boundary-data)\n\n---\n**APIs and web services**\nThis dataset is available via ArcGIS Online and ArcGIS REST services, as well as our standard APIs.\n[LDS APIs and OGC web services](https://data.linz.govt.nz/layer/50804-nz-property-titles/services/)\n[ArcGIS Online map services](https://linz.maps.arcgis.com/home/item.html?id=11ba5960f1d7472781310ad93ff2d9c6)",
    "description_html": '<p>This dataset provides title information (excluding ownership) where there is a relationship to one or more primary parcels.</p>\n<p>A Record of Title is a record of a property\'s owners, legal description and the rights and responsibilities  registered against the title.This dataset does not contain any ownership information so that it can be freely distributed. If ownership information is required, you need to <a href="https://www.linz.govt.nz/products-services/data/licensing-and-using-data/linz-licence-personal-data">apply for access</a>.</p>\n<p>There can be multiple parcels associated with a title, and a title may only have a part share in a parcel. This means the shape representing the title will be an aggregation of all parcels that the title is associated with. The ‘spatial extents shared’ attribute when equal to ‘false’ will indicate that title has exclusive interest over all of the shape (this will be case for the vast majority).</p>\n<p>The originating data for parcel/title associations includes some non-official sources where the official data does not support a link. For more information see the <a href="https://www.linz.govt.nz/products-services/data/types-linz-data/property-ownership-and-boundary-data/types-lds-property-ownership-and-boundary-data">LINZ website</a></p>\n<hr>\n<p><strong>APIs and web services</strong><br>\nThis dataset is available via ArcGIS Online and ArcGIS REST services, as well as our standard APIs.<br>\n<a href="https://data.linz.govt.nz/layer/50804-nz-property-titles/services/">LDS APIs and OGC web services</a><br>\n<a href="https://linz.maps.arcgis.com/home/item.html?id=11ba5960f1d7472781310ad93ff2d9c6">ArcGIS Online map services</a></p>',
    "group": {
        "id": 2101,
        "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2101/",
        "name": "Survey & Title",
        "country": "NZ",
        "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
        "type": "normal",
    },
    "publisher": {
        "id": "data.linz.govt.nz",
        "name": "Land Information New Zealand",
        "html_url": "https://data.linz.govt.nz/",
        "slug_for_url": null,
        "theme": {
            "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
            "background_color": "004964",
        },
        "site": {"url": "https://data.linz.govt.nz", "name": "LINZ Data Service"},
        "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
        "flags": {},
        "description": null,
    },
    "data": {
        "storage": "classic",
        "datasources": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/datasources/",
        "fields": [
            {"name": "id", "type": "integer"},
            {"name": "title_no", "type": "string"},
            {"name": "status", "type": "string"},
            {"name": "type", "type": "string"},
            {"name": "land_district", "type": "string"},
            {"name": "issue_date", "type": "datetime"},
            {"name": "guarantee_status", "type": "string"},
            {"name": "estate_description", "type": "string"},
            {"name": "number_owners", "type": "bigint"},
            {"name": "spatial_extents_shared", "type": "boolean"},
            {"name": "shape", "type": "geometry"},
        ],
        "encoding": "utf-8",
        "crs": {
            "id": "EPSG:4167",
            "url": "https://data.linz.govt.nz/services/api/v1.x/coordinate-systems/EPSG:4167/",
            "name": "NZGD2000",
            "kind": "geographic 2D",
            "unit_horizontal": "degree",
            "unit_vertical": "",
            "url_external": "https://epsg.io/4167",
            "component_horizontal": null,
            "component_vertical": null,
            "srid": 4167,
        },
        "primary_key_fields": ["id"],
        "geometry_field": "shape",
        "geometry_type": "multipolygon",
        "source_revision": 5811,
        "omitted_fields": [],
        "tile_revision": 422056,
        "feature_count": 2414374,
        "extent": {
            "type": "Polygon",
            "coordinates": [
                [
                    [166.59999990000003, -47.28999358208071],
                    [166.59999990000003, -34.12963455],
                    [184.20000009999998, -34.12963455],
                    [184.20000009999998, -47.28999358208071],
                    [166.59999990000003, -47.28999358208071],
                ]
            ],
        },
        "datasource_count": 1,
        "change_summary": {
            "inserted": 836,
            "updated": 4289,
            "deleted": 382,
            "schema_changes": {
                "added": [],
                "changed": [],
                "removed": [],
                "srid_changed": false,
                "geometry_type_changed": false,
                "primary_keys_changed": false,
            },
        },
        "source_summary": {"formats": ["Postgres"], "types": ["PostgreSQL"]},
        "import_started_at": "2025-05-16T16:11:52.605738Z",
        "import_ended_at": "2025-05-16T16:42:50.963636Z",
        "import_log": {
            "invalid_geometries": 0,
            "messages": 0,
            "url": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/data/import-log/",
        },
        "import_version": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/",
        "update_available": false,
        "sample": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/data/sample/",
        "raster_resolution": null,
        "empty_geometry_count": 259,
        "has_z": false,
        "export_formats": [
            {"name": "Shapefile", "mimetype": "application/x-zipped-shp"},
            {"name": "MapInfo TAB", "mimetype": "application/x-ogc-mapinfo_file"},
            {
                "name": "MapInfo MIF",
                "mimetype": "application/x-ogc-mapinfo_file+mif",
            },
            {"name": "CSV", "mimetype": "text/csv"},
            {"name": "GeoPackage / SQLite", "mimetype": "application/x-ogc-gpkg"},
            {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
            {"name": "KML", "mimetype": "application/vnd.google-earth.kml+xml"},
            {"name": "DWG", "mimetype": "image/vnd.dwg"},
            {"name": "PDF", "mimetype": "application/pdf"},
        ],
    },
    "url_html": "https://data.linz.govt.nz/layer/50804-nz-property-titles/",
    "url_canonical": "https://data.linz.govt.nz/layer/50804-nz-property-titles/",
    "published_version": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/",
    "this_version": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/",
    "kind": "vector",
    "categories": [
        {
            "name": "Titles & Owners",
            "slug": "titles-owners",
            "key": "property-ownership-boundaries/titles-owners",
            "url": "https://data.linz.govt.nz/services/api/v1.x/categories/property-ownership-boundaries/titles-owners/",
            "ancestors": [
                {
                    "name": "Property Ownership & Boundaries",
                    "slug": "property-ownership-boundaries",
                    "key": "property-ownership-boundaries",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/categories/property-ownership-boundaries/",
                }
            ],
        }
    ],
    "tags": ["New Zealand"],
    "collected_at": null,
    "created_at": "2011-05-31T06:53:10.949836Z",
    "license": {
        "id": 171,
        "title": "Creative Commons Attribution 4.0 International",
        "type": "cc-by",
        "jurisdiction": "",
        "version": "4.0",
        "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
        "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
        "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
    },
    "metadata": {
        "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253815/metadata-resources/22137/",
        "native": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/metadata/",
        "iso": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/metadata/iso/",
        "dc": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/metadata/dc/",
    },
    "elevation_field": "",
    "styles": [],
    "default_style": null,
    "attachments": [
        {
            "id": 11012,
            "url": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/attachments/11012/",
            "url_download": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/attachments/11012/download/",
            "url_html": "https://data.linz.govt.nz/layer/50804-nz-property-titles/attachments/11012/",
            "document": {
                "id": 11012,
                "title": "Property and Ownership Simplified Tables Data Dictionary",
                "url": "https://data.linz.govt.nz/services/api/v1.x/documents/11012/",
                "type": "document",
                "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/documents/11012/27007/thumb-1200x630.png",
                "first_published_at": "2013-04-11T23:49:40Z",
                "published_at": "2024-07-07T22:16:48.776126Z",
                "user_capabilities": ["can-star", "can-export"],
                "group": {
                    "id": 2101,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2101/",
                    "name": "Survey & Title",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "url_html": "https://data.linz.govt.nz/document/11012-property-and-ownership-simplified-tables-data-dictionary/",
                "url_download": "https://data.linz.govt.nz/services/api/v1.x/documents/11012/versions/27007/download/",
                "extension": "pdf",
                "file_size": 406891,
                "file_size_formatted": "406 KB",
                "featured_at": null,
                "user_permissions": ["find", "view", "download"],
                "description": "This document provides detailed metadata and relationships for the simplified property and ownership tabular data as released on the LINZ Data Service.",
                "description_html": "<p>This document provides detailed metadata and relationships for the simplified property and ownership tabular data as released on the LINZ Data Service.</p>",
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/documents/11012/versions/27007/",
                "latest_version": "https://data.linz.govt.nz/services/api/v1.x/documents/11012/versions/27007/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/documents/11012/versions/27007/",
                "data": {"datasource": null},
                "categories": [
                    {
                        "name": "Property Ownership & Boundaries",
                        "slug": "property-ownership-boundaries",
                        "key": "property-ownership-boundaries",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/property-ownership-boundaries/",
                        "ancestors": [],
                    }
                ],
                "tags": ["owners", "title"],
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": null,
                "attached": "https://data.linz.govt.nz/services/api/v1.x/documents/11012/attached/",
                "settings": {"feedback_enabled": true},
                "num_views": 57091,
                "num_downloads": 31515,
                "url_canonical": "https://data.linz.govt.nz/document/11012-property-and-ownership-simplified-tables-data-dictionary/",
                "is_starred": false,
                "version": {
                    "id": 27007,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/documents/11012/versions/27007/",
                    "created_at": "2024-07-07T22:16:38.928066Z",
                    "created_by": {
                        "id": 243309,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/users/243309/",
                        "first_name": "Megan",
                        "last_name": "Davidson",
                        "country": "NZ",
                        "geotag": "global/oceania/new-zealand",
                    },
                },
                "public_access": "download",
            },
        }
    ],
    "settings": {
        "is_pinned": null,
        "feedback_enabled": true,
        "is_source_mirror": false,
    },
    "repository": {
        "id": "b8mdlRq",
        "full_name": "linz/nz-property-titles",
        "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/nz-property-titles/",
        "clone_location_ssh": "kart@data.koordinates.com:linz/nz-property-titles",
        "clone_location_https": "https://data.koordinates.com/linz/nz-property-titles",
        "type": "repo",
        "title": "NZ Property Titles",
        "first_published_at": "2023-08-08T20:48:54.370306Z",
        "published_at": null,
        "settings": {"feedback_enabled": true},
        "user_capabilities": ["can-star", "can-clone"],
        "user_permissions": ["find", "view", "download"],
    },
    "geotags": [
        {
            "country_code": "NZ",
            "state_code": null,
            "name": "New Zealand",
            "key": "global/oceania/new-zealand",
        }
    ],
    "num_views": 1246216,
    "num_downloads": 194039,
    "is_starred": false,
    "public_access": "download",
    "version": {
        "id": 413899,
        "url": "https://data.linz.govt.nz/services/api/v1.x/layers/50804/versions/413899/",
        "status": "ok",
        "created_at": "2025-05-16T15:03:07.997917Z",
        "reference": "",
        "progress": 1.0,
        "data_import": true,
    },
}
