set_ = {
    request: "https://data.linz.govt.nz/services/api/v1.x/sets/7364/",
    response: {
        "id": 7364,
        "title": "NZ Suburbs and Localities Dataset",
        "url": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/",
        "type": "set",
        "created_at": "2023-06-19T03:53:42.141095Z",
        "thumbnail_url": "https://tiles-cdn.koordinates.com/services/tiles/v4/thumbnail/set=7364.2190,style=auto/1200x630.png",
        "kind": "mixed",
        "item_count": 7,
        "featured_at": null,
        "published_at": "2023-06-20T03:25:57.799429Z",
        "first_published_at": "2023-06-19T03:53:47.680455Z",
        "user_capabilities": ["can-star"],
        "user_permissions": ["find", "view"],
        "is_starred": false,
        "description": "The data model is made up of a spatial table with six related tables, and used to store and maintain the data before creating the NZ Suburbs and Localities layer.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
        "description_html": '<p>The data model is made up of a spatial table with six related tables, and used to store and maintain the data before creating the NZ Suburbs and Localities layer.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
        "latest_version": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/versions/2190/",
        "published_version": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/versions/2190/",
        "this_version": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/versions/2190/",
        "publisher": {
            "id": "data.linz.govt.nz",
            "name": "Land Information New Zealand",
            "html_url": "https://data.linz.govt.nz/",
            "slug_for_url": null,
            "theme": {
                "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                "background_color": "004964",
            },
            "site": {"url": "https://data.linz.govt.nz", "name": "LINZ Data Service"},
            "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
            "flags": {},
            "description": null,
        },
        "categories": [
            {
                "name": "Suburbs and Localities",
                "slug": "suburbs-and-localities",
                "key": "suburbs-and-localities",
                "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                "ancestors": [],
            }
        ],
        "tags": [],
        "group": {
            "id": 2174,
            "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
            "name": "Addressing",
            "country": "NZ",
            "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
            "type": "normal",
        },
        "url_html": "https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/",
        "metadata": {
            "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253405/metadata-resources/21858/",
            "native": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/versions/2190/metadata/",
            "iso": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/versions/2190/metadata/iso/",
            "dc": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/versions/2190/metadata/dc/",
        },
        "styles": [],
        "extent": {
            "type": "Polygon",
            "coordinates": [
                [
                    [166.39999990000004, -47.29000207115998],
                    [166.39999990000004, -34.12956488266628],
                    [183.9000001, -34.12956488266628],
                    [183.9000001, -47.29000207115998],
                    [166.39999990000004, -47.29000207115998],
                ]
            ],
        },
        "default_style": null,
        "settings": {"feedback_enabled": true},
        "num_views": 6193,
        "geotags": [
            {
                "country_code": "NZ",
                "state_code": null,
                "name": "New Zealand",
                "key": "global/oceania/new-zealand",
            }
        ],
        "public_access": "view",
        "services": [
            {
                "id": "s3V8qd5crgRFyQ6",
                "authority": "koordinates",
                "key": "spatial-query-set",
                "short_name": "Spatial Query API",
                "label": "Set Query API",
                "auth_method": ["apikey"],
                "auth_scopes": ["query"],
                "domain": "data.linz.govt.nz",
                "template_urls": [
                    {
                        "name": "Set JSON Query",
                        "service_url": "https://data.linz.govt.nz/services/query/v1/set.json?key=[api_token]&set=7364&x=[x]&y=[y]",
                    }
                ],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/services/s3V8qd5crgRFyQ6/permissions/",
                "advertised": true,
                "user_capabilities": [],
                "enabled": true,
            }
        ],
        "items": [
            {
                "id": 113763,
                "url": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/",
                "type": "layer",
                "title": "Suburb Locality",
                "first_published_at": "2023-06-16T04:22:10.494662Z",
                "thumbnail_url": "https://tiles-cdn.koordinates.com/services/tiles/v4/thumbnail/layer=113763.422177,style=auto/1200x630.png",
                "published_at": "2025-05-19T23:34:00.462860Z",
                "featured_at": null,
                "services": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/services/",
                "user_capabilities": [
                    "can-star",
                    "can-export",
                    "can-spatial-query",
                    "can-view-data-table",
                ],
                "user_permissions": ["find", "view", "download"],
                "description": "The Suburb Locality layer is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). This layer contains the identifier and key information of suburbs and localities data including names and types.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
                "description_html": '<p>The Suburb Locality layer is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. This layer contains the identifier and key information of suburbs and localities data including names and types.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
                "group": {
                    "id": 2174,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
                    "name": "Addressing",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "data": {
                    "storage": "classic",
                    "datasources": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/datasources/",
                    "fields": [
                        {"name": "shape", "type": "geometry"},
                        {"name": "id", "type": "integer"},
                        {"name": "parent_id", "type": "integer"},
                        {"name": "name", "type": "string"},
                        {"name": "type", "type": "string"},
                        {"name": "start_date", "type": "date"},
                        {"name": "name_ascii", "type": "string"},
                    ],
                    "encoding": null,
                    "crs": {
                        "id": "EPSG:4167",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/coordinate-systems/EPSG:4167/",
                        "name": "NZGD2000",
                        "kind": "geographic 2D",
                        "unit_horizontal": "degree",
                        "unit_vertical": "",
                        "url_external": "https://epsg.io/4167",
                        "component_horizontal": null,
                        "component_vertical": null,
                        "srid": 4167,
                    },
                    "primary_key_fields": ["id"],
                    "geometry_field": "shape",
                    "geometry_type": "multipolygon",
                    "omitted_fields": [],
                    "tile_revision": 422177,
                    "feature_count": 6562,
                    "extent": {
                        "type": "Polygon",
                        "coordinates": [
                            [
                                [166.39999990000004, -47.29000207115998],
                                [166.39999990000004, -34.12956488266628],
                                [183.9000001, -34.12956488266628],
                                [183.9000001, -47.29000207115998],
                                [166.39999990000004, -47.29000207115998],
                            ]
                        ],
                    },
                    "datasource_count": 1,
                    "change_summary": {
                        "inserted": 0,
                        "updated": 34,
                        "deleted": 1,
                        "schema_changes": {
                            "added": [],
                            "changed": [],
                            "removed": [],
                            "srid_changed": false,
                            "geometry_type_changed": false,
                            "primary_keys_changed": false,
                        },
                    },
                    "source_summary": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/data/source-summary/",
                    "import_started_at": "2025-05-19T23:30:37.365286Z",
                    "import_ended_at": "2025-05-19T23:31:57.755021Z",
                    "import_log": {
                        "invalid_geometries": 1,
                        "messages": 0,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/data/import-log/",
                    },
                    "import_version": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/",
                    "update_available": false,
                    "sample": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/data/sample/",
                    "raster_resolution": null,
                    "empty_geometry_count": 0,
                    "has_z": false,
                    "export_formats": [
                        {"name": "Shapefile", "mimetype": "application/x-zipped-shp"},
                        {
                            "name": "MapInfo TAB",
                            "mimetype": "application/x-ogc-mapinfo_file",
                        },
                        {
                            "name": "MapInfo MIF",
                            "mimetype": "application/x-ogc-mapinfo_file+mif",
                        },
                        {"name": "CSV", "mimetype": "text/csv"},
                        {
                            "name": "GeoPackage / SQLite",
                            "mimetype": "application/x-ogc-gpkg",
                        },
                        {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
                        {
                            "name": "KML",
                            "mimetype": "application/vnd.google-earth.kml+xml",
                        },
                        {"name": "DWG", "mimetype": "image/vnd.dwg"},
                        {"name": "PDF", "mimetype": "application/pdf"},
                    ],
                },
                "url_html": "https://data.linz.govt.nz/layer/113763-suburb-locality/",
                "url_canonical": "https://data.linz.govt.nz/layer/113763-suburb-locality/",
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/",
                "kind": "vector",
                "categories": [
                    {
                        "name": "Suburbs and Localities",
                        "slug": "suburbs-and-localities",
                        "key": "suburbs-and-localities",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                        "ancestors": [],
                    }
                ],
                "tags": ["New Zealand"],
                "collected_at": null,
                "created_at": "2023-06-16T04:16:09.961455Z",
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": {
                    "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253867/metadata-resources/22228/",
                    "native": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/metadata/",
                    "iso": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/metadata/iso/",
                    "dc": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/metadata/dc/",
                },
                "elevation_field": "",
                "styles": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/styles/",
                "default_style": null,
                "attachments": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/attachments/",
                "settings": {
                    "is_pinned": null,
                    "feedback_enabled": true,
                    "is_source_mirror": false,
                },
                "repository": {
                    "id": "QqoKz2q",
                    "full_name": "linz/suburb-locality",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality/",
                    "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality",
                    "clone_location_https": "https://data.koordinates.com/linz/suburb-locality",
                    "type": "repo",
                    "title": "Suburb Locality",
                    "first_published_at": "2023-08-09T00:03:34.828986Z",
                    "published_at": null,
                    "settings": {"feedback_enabled": true},
                    "user_capabilities": ["can-star", "can-clone"],
                    "user_permissions": ["find", "view", "download"],
                },
                "geotags": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/geotags/",
                "num_views": 6619,
                "num_downloads": 978,
                "is_starred": false,
                "public_access": "download",
                "version": {
                    "id": 414045,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/layers/113763/versions/414045/",
                    "status": "ok",
                    "created_at": "2025-05-19T23:30:33.363846Z",
                    "reference": "",
                    "progress": 1.0,
                    "data_import": true,
                },
            },
            {
                "id": 110596,
                "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/",
                "type": "table",
                "title": "Suburb Locality - Territorial Authority",
                "first_published_at": "2022-10-03T23:54:26.717000Z",
                "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/110596/422176/og.png",
                "published_at": "2025-05-19T23:31:41.668694Z",
                "featured_at": null,
                "services": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/services/",
                "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
                "user_permissions": ["find", "view", "download"],
                "description": "The Territorial Authority data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). This table contains the linkage between suburbs and localities data and Territorial Authorities. Most suburbs and localities are located in one or multiple Territorial Authorities. Please note some offshore islands are not included in Territorial Authority boundaries.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
                "description_html": '<p>The Territorial Authority data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. This table contains the linkage between suburbs and localities data and Territorial Authorities. Most suburbs and localities are located in one or multiple Territorial Authorities. Please note some offshore islands are not included in Territorial Authority boundaries.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
                "group": {
                    "id": 2174,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
                    "name": "Addressing",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "data": {
                    "storage": "classic",
                    "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/datasources/",
                    "fields": [
                        {"name": "id", "type": "integer"},
                        {"name": "suburb_locality_id", "type": "integer"},
                        {"name": "territorial_authority", "type": "string"},
                        {"name": "territorial_authority_ascii", "type": "string"},
                    ],
                    "encoding": "utf-8",
                    "crs": null,
                    "primary_key_fields": ["id"],
                    "geometry_field": null,
                    "geometry_type": "",
                    "omitted_fields": [],
                    "tile_revision": 422176,
                    "feature_count": 5912,
                    "extent": null,
                    "datasource_count": 1,
                    "change_summary": {
                        "inserted": 0,
                        "updated": 0,
                        "deleted": 0,
                        "schema_changes": {
                            "added": [],
                            "changed": [],
                            "removed": [],
                            "srid_changed": false,
                            "geometry_type_changed": false,
                            "primary_keys_changed": false,
                        },
                    },
                    "source_summary": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/data/source-summary/",
                    "import_started_at": "2025-05-19T23:30:31.436098Z",
                    "import_ended_at": "2025-05-19T23:30:42.231687Z",
                    "import_log": {
                        "invalid_geometries": 0,
                        "messages": 0,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/data/import-log/",
                    },
                    "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/",
                    "update_available": false,
                    "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/data/sample/",
                    "raster_resolution": null,
                    "empty_geometry_count": 5912,
                    "has_z": false,
                    "export_formats": [
                        {
                            "name": "DBF (dBase III)",
                            "mimetype": "application/x-zipped-shp",
                        },
                        {
                            "name": "MapInfo TAB",
                            "mimetype": "application/x-ogc-mapinfo_file",
                        },
                        {
                            "name": "MapInfo MIF",
                            "mimetype": "application/x-ogc-mapinfo_file+mif",
                        },
                        {"name": "CSV", "mimetype": "text/csv"},
                        {
                            "name": "GeoPackage / SQLite",
                            "mimetype": "application/x-ogc-gpkg",
                        },
                        {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
                    ],
                },
                "url_html": "https://data.linz.govt.nz/table/110596-suburb-locality-territorial-authority/",
                "url_canonical": "https://data.linz.govt.nz/table/110596-suburb-locality-territorial-authority/",
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/",
                "kind": "table",
                "categories": [
                    {
                        "name": "Suburbs and Localities",
                        "slug": "suburbs-and-localities",
                        "key": "suburbs-and-localities",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                        "ancestors": [],
                    }
                ],
                "tags": ["New Zealand"],
                "collected_at": null,
                "created_at": "2022-10-03T23:53:23.072931Z",
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": {
                    "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253861/metadata-resources/22222/",
                    "native": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/metadata/",
                    "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/metadata/iso/",
                    "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/metadata/dc/",
                },
                "elevation_field": "id",
                "attachments": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/attachments/",
                "settings": {
                    "is_pinned": null,
                    "feedback_enabled": true,
                    "is_source_mirror": false,
                },
                "repository": {
                    "id": "ZqvjJBq",
                    "full_name": "linz/suburb-locality-territorial-authority",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-territorial-authority/",
                    "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-territorial-authority",
                    "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-territorial-authority",
                    "type": "repo",
                    "title": "Suburb Locality - Territorial Authority",
                    "first_published_at": "2023-08-08T12:16:48.505633Z",
                    "published_at": null,
                    "settings": {"feedback_enabled": true},
                    "user_capabilities": ["can-star", "can-clone"],
                    "user_permissions": ["find", "view", "download"],
                },
                "geotags": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/geotags/",
                "num_views": 2631,
                "num_downloads": 480,
                "is_starred": false,
                "public_access": "download",
                "version": {
                    "id": 414044,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110596/versions/414044/",
                    "status": "ok",
                    "created_at": "2025-05-19T23:30:24.427595Z",
                    "reference": "",
                    "progress": 1.0,
                    "data_import": true,
                },
            },
            {
                "id": 113008,
                "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/",
                "type": "table",
                "title": "Suburb Locality - NZ Gazetteer",
                "first_published_at": "2023-04-04T19:46:48.627771Z",
                "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/113008/422175/og.png",
                "published_at": "2025-05-19T23:31:27.063274Z",
                "featured_at": null,
                "services": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/services/",
                "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
                "user_permissions": ["find", "view", "download"],
                "description": "The NZ Gazetteer data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). This table contains the linkage between the NZ Suburbs and Localities data and NZGB official place name.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
                "description_html": '<p>The NZ Gazetteer data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. This table contains the linkage between the NZ Suburbs and Localities data and NZGB official place name.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
                "group": {
                    "id": 2174,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
                    "name": "Addressing",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "data": {
                    "storage": "classic",
                    "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/datasources/",
                    "fields": [
                        {"name": "id", "type": "integer"},
                        {"name": "suburb_locality_id", "type": "integer"},
                        {"name": "name_id", "type": "integer"},
                        {"name": "feat_id", "type": "integer"},
                    ],
                    "encoding": "utf-8",
                    "crs": null,
                    "primary_key_fields": ["id"],
                    "geometry_field": null,
                    "geometry_type": "",
                    "omitted_fields": [],
                    "tile_revision": 422175,
                    "feature_count": 6346,
                    "extent": null,
                    "datasource_count": 1,
                    "change_summary": {
                        "inserted": 0,
                        "updated": 0,
                        "deleted": 0,
                        "schema_changes": {
                            "added": [],
                            "changed": [],
                            "removed": [],
                            "srid_changed": false,
                            "geometry_type_changed": false,
                            "primary_keys_changed": false,
                        },
                    },
                    "source_summary": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/data/source-summary/",
                    "import_started_at": "2025-05-19T23:30:26.215088Z",
                    "import_ended_at": "2025-05-19T23:30:33.422546Z",
                    "import_log": {
                        "invalid_geometries": 0,
                        "messages": 0,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/data/import-log/",
                    },
                    "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/",
                    "update_available": false,
                    "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/data/sample/",
                    "raster_resolution": null,
                    "empty_geometry_count": 6346,
                    "has_z": false,
                    "export_formats": [
                        {
                            "name": "DBF (dBase III)",
                            "mimetype": "application/x-zipped-shp",
                        },
                        {
                            "name": "MapInfo TAB",
                            "mimetype": "application/x-ogc-mapinfo_file",
                        },
                        {
                            "name": "MapInfo MIF",
                            "mimetype": "application/x-ogc-mapinfo_file+mif",
                        },
                        {"name": "CSV", "mimetype": "text/csv"},
                        {
                            "name": "GeoPackage / SQLite",
                            "mimetype": "application/x-ogc-gpkg",
                        },
                        {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
                    ],
                },
                "url_html": "https://data.linz.govt.nz/table/113008-suburb-locality-nz-gazetteer/",
                "url_canonical": "https://data.linz.govt.nz/table/113008-suburb-locality-nz-gazetteer/",
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/",
                "kind": "table",
                "categories": [
                    {
                        "name": "Suburbs and Localities",
                        "slug": "suburbs-and-localities",
                        "key": "suburbs-and-localities",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                        "ancestors": [],
                    }
                ],
                "tags": ["New Zealand"],
                "collected_at": null,
                "created_at": "2023-04-04T19:46:00.908324Z",
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": {
                    "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253864/metadata-resources/22225/",
                    "native": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/metadata/",
                    "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/metadata/iso/",
                    "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/metadata/dc/",
                },
                "elevation_field": "",
                "attachments": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/attachments/",
                "settings": {
                    "is_pinned": null,
                    "feedback_enabled": true,
                    "is_source_mirror": false,
                },
                "repository": {
                    "id": "GxEVg1q",
                    "full_name": "linz/suburb-locality-nz-gazetteer",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-nz-gazetteer/",
                    "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-nz-gazetteer",
                    "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-nz-gazetteer",
                    "type": "repo",
                    "title": "Suburb Locality - NZ Gazetteer",
                    "first_published_at": "2023-08-08T16:57:56.844544Z",
                    "published_at": null,
                    "settings": {"feedback_enabled": true},
                    "user_capabilities": ["can-star", "can-clone"],
                    "user_permissions": ["find", "view", "download"],
                },
                "geotags": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/geotags/",
                "num_views": 876,
                "num_downloads": 363,
                "is_starred": false,
                "public_access": "download",
                "version": {
                    "id": 414043,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113008/versions/414043/",
                    "status": "ok",
                    "created_at": "2025-05-19T23:30:19.732751Z",
                    "reference": "",
                    "progress": 1.0,
                    "data_import": true,
                },
            },
            {
                "id": 113014,
                "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/",
                "type": "table",
                "title": "Suburb Locality - Major Name",
                "first_published_at": "2023-04-04T20:12:16.852039Z",
                "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/113014/422174/og.png",
                "published_at": "2025-05-19T23:31:34.917071Z",
                "featured_at": null,
                "services": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/services/",
                "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
                "user_permissions": ["find", "view", "download"],
                "description": "The Major Name data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). Major names describe the wider area in which the boundary is located.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
                "description_html": '<p>The Major Name data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. Major names describe the wider area in which the boundary is located.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
                "group": {
                    "id": 2174,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
                    "name": "Addressing",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "data": {
                    "storage": "classic",
                    "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/datasources/",
                    "fields": [
                        {"name": "id", "type": "integer"},
                        {"name": "suburb_locality_id", "type": "integer"},
                        {"name": "major_name_id", "type": "integer"},
                        {"name": "major_name", "type": "string"},
                        {"name": "major_name_type", "type": "string"},
                        {"name": "major_name_ascii", "type": "string"},
                    ],
                    "encoding": "utf-8",
                    "crs": null,
                    "primary_key_fields": ["id"],
                    "geometry_field": null,
                    "geometry_type": "",
                    "omitted_fields": [],
                    "tile_revision": 422174,
                    "feature_count": 3346,
                    "extent": null,
                    "datasource_count": 1,
                    "change_summary": {
                        "inserted": 0,
                        "updated": 1,
                        "deleted": 0,
                        "schema_changes": {
                            "added": [],
                            "changed": [],
                            "removed": [],
                            "srid_changed": false,
                            "geometry_type_changed": false,
                            "primary_keys_changed": false,
                        },
                    },
                    "source_summary": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/data/source-summary/",
                    "import_started_at": "2025-05-19T23:30:21.328607Z",
                    "import_ended_at": "2025-05-19T23:30:29.945424Z",
                    "import_log": {
                        "invalid_geometries": 0,
                        "messages": 0,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/data/import-log/",
                    },
                    "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/",
                    "update_available": false,
                    "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/data/sample/",
                    "raster_resolution": null,
                    "empty_geometry_count": 3346,
                    "has_z": false,
                    "export_formats": [
                        {
                            "name": "DBF (dBase III)",
                            "mimetype": "application/x-zipped-shp",
                        },
                        {
                            "name": "MapInfo TAB",
                            "mimetype": "application/x-ogc-mapinfo_file",
                        },
                        {
                            "name": "MapInfo MIF",
                            "mimetype": "application/x-ogc-mapinfo_file+mif",
                        },
                        {"name": "CSV", "mimetype": "text/csv"},
                        {
                            "name": "GeoPackage / SQLite",
                            "mimetype": "application/x-ogc-gpkg",
                        },
                        {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
                    ],
                },
                "url_html": "https://data.linz.govt.nz/table/113014-suburb-locality-major-name/",
                "url_canonical": "https://data.linz.govt.nz/table/113014-suburb-locality-major-name/",
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/",
                "kind": "table",
                "categories": [
                    {
                        "name": "Suburbs and Localities",
                        "slug": "suburbs-and-localities",
                        "key": "suburbs-and-localities",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                        "ancestors": [],
                    }
                ],
                "tags": ["New Zealand"],
                "collected_at": null,
                "created_at": "2023-04-04T20:11:22.605782Z",
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": {
                    "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253863/metadata-resources/22224/",
                    "native": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/metadata/",
                    "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/metadata/iso/",
                    "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/metadata/dc/",
                },
                "elevation_field": "",
                "attachments": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/attachments/",
                "settings": {
                    "is_pinned": null,
                    "feedback_enabled": true,
                    "is_source_mirror": false,
                },
                "repository": {
                    "id": "RqQEbrq",
                    "full_name": "linz/suburb-locality-major-name",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-major-name/",
                    "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-major-name",
                    "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-major-name",
                    "type": "repo",
                    "title": "Suburb Locality - Major Name",
                    "first_published_at": "2023-08-09T19:38:10.386580Z",
                    "published_at": null,
                    "settings": {"feedback_enabled": true},
                    "user_capabilities": ["can-star", "can-clone"],
                    "user_permissions": ["find", "view", "download"],
                },
                "geotags": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/geotags/",
                "num_views": 1482,
                "num_downloads": 509,
                "is_starred": false,
                "public_access": "download",
                "version": {
                    "id": 414042,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113014/versions/414042/",
                    "status": "ok",
                    "created_at": "2025-05-19T23:30:15.524121Z",
                    "reference": "",
                    "progress": 1.0,
                    "data_import": true,
                },
            },
            {
                "id": 110594,
                "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/",
                "type": "table",
                "title": "Suburb Locality - Adjacent Name",
                "first_published_at": "2022-10-03T23:51:23.939587Z",
                "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/110594/422173/og.png",
                "published_at": "2025-05-19T23:31:37.398061Z",
                "featured_at": null,
                "services": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/services/",
                "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
                "user_permissions": ["find", "view", "download"],
                "description": "The Adjacent Name data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). This table enables users to identify all neighbouring suburbs and localities.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
                "description_html": '<p>The Adjacent Name data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. This table enables users to identify all neighbouring suburbs and localities.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
                "group": {
                    "id": 2174,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
                    "name": "Addressing",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "data": {
                    "storage": "classic",
                    "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/datasources/",
                    "fields": [
                        {"name": "id", "type": "integer"},
                        {"name": "suburb_locality_id", "type": "integer"},
                        {"name": "adjacent_id", "type": "integer"},
                    ],
                    "encoding": "utf-8",
                    "crs": null,
                    "primary_key_fields": ["id"],
                    "geometry_field": null,
                    "geometry_type": "",
                    "omitted_fields": [],
                    "tile_revision": 422173,
                    "feature_count": 29390,
                    "extent": null,
                    "datasource_count": 1,
                    "change_summary": {
                        "inserted": 0,
                        "updated": 0,
                        "deleted": 0,
                        "schema_changes": {
                            "added": [],
                            "changed": [],
                            "removed": [],
                            "srid_changed": false,
                            "geometry_type_changed": false,
                            "primary_keys_changed": false,
                        },
                    },
                    "source_summary": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/data/source-summary/",
                    "import_started_at": "2025-05-19T23:30:16.651966Z",
                    "import_ended_at": "2025-05-19T23:30:36.099482Z",
                    "import_log": {
                        "invalid_geometries": 0,
                        "messages": 0,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/data/import-log/",
                    },
                    "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/",
                    "update_available": false,
                    "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/data/sample/",
                    "raster_resolution": null,
                    "empty_geometry_count": 29390,
                    "has_z": false,
                    "export_formats": [
                        {
                            "name": "DBF (dBase III)",
                            "mimetype": "application/x-zipped-shp",
                        },
                        {
                            "name": "MapInfo TAB",
                            "mimetype": "application/x-ogc-mapinfo_file",
                        },
                        {
                            "name": "MapInfo MIF",
                            "mimetype": "application/x-ogc-mapinfo_file+mif",
                        },
                        {"name": "CSV", "mimetype": "text/csv"},
                        {
                            "name": "GeoPackage / SQLite",
                            "mimetype": "application/x-ogc-gpkg",
                        },
                        {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
                    ],
                },
                "url_html": "https://data.linz.govt.nz/table/110594-suburb-locality-adjacent-name/",
                "url_canonical": "https://data.linz.govt.nz/table/110594-suburb-locality-adjacent-name/",
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/",
                "kind": "table",
                "categories": [
                    {
                        "name": "Suburbs and Localities",
                        "slug": "suburbs-and-localities",
                        "key": "suburbs-and-localities",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                        "ancestors": [],
                    }
                ],
                "tags": ["New Zealand"],
                "collected_at": null,
                "created_at": "2022-10-03T23:50:11.168734Z",
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": {
                    "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253865/metadata-resources/22226/",
                    "native": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/metadata/",
                    "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/metadata/iso/",
                    "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/metadata/dc/",
                },
                "elevation_field": "",
                "attachments": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/attachments/",
                "settings": {
                    "is_pinned": null,
                    "feedback_enabled": true,
                    "is_source_mirror": false,
                },
                "repository": {
                    "id": "BqGNdwx",
                    "full_name": "linz/suburb-locality-adjacent-name",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-adjacent-name/",
                    "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-adjacent-name",
                    "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-adjacent-name",
                    "type": "repo",
                    "title": "Suburb Locality - Adjacent Name",
                    "first_published_at": "2023-08-08T09:07:58.563374Z",
                    "published_at": null,
                    "settings": {"feedback_enabled": true},
                    "user_capabilities": ["can-star", "can-clone"],
                    "user_permissions": ["find", "view", "download"],
                },
                "geotags": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/geotags/",
                "num_views": 487,
                "num_downloads": 393,
                "is_starred": false,
                "public_access": "download",
                "version": {
                    "id": 414041,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110594/versions/414041/",
                    "status": "ok",
                    "created_at": "2025-05-19T23:30:10.838409Z",
                    "reference": "",
                    "progress": 1.0,
                    "data_import": true,
                },
            },
            {
                "id": 110593,
                "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/",
                "type": "table",
                "title": "Suburb Locality - Additional Name",
                "first_published_at": "2022-10-03T23:01:43.968135Z",
                "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/110593/422172/og.png",
                "published_at": "2025-05-19T23:31:26.925006Z",
                "featured_at": null,
                "services": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/services/",
                "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
                "user_permissions": ["find", "view", "download"],
                "description": "The Additional Name data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). The intention of the additional name field is to capture any common, in use names for the suburb or locality.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
                "description_html": '<p>The Additional Name data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. The intention of the additional name field is to capture any common, in use names for the suburb or locality.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
                "group": {
                    "id": 2174,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
                    "name": "Addressing",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "data": {
                    "storage": "classic",
                    "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/datasources/",
                    "fields": [
                        {"name": "id", "type": "integer"},
                        {"name": "suburb_locality_id", "type": "integer"},
                        {"name": "additional_name", "type": "string"},
                        {"name": "additional_name_ascii", "type": "string"},
                    ],
                    "encoding": "utf-8",
                    "crs": null,
                    "primary_key_fields": ["id"],
                    "geometry_field": null,
                    "geometry_type": "",
                    "omitted_fields": [],
                    "tile_revision": 422172,
                    "feature_count": 6223,
                    "extent": null,
                    "datasource_count": 1,
                    "change_summary": {
                        "inserted": 0,
                        "updated": 0,
                        "deleted": 0,
                        "schema_changes": {
                            "added": [],
                            "changed": [],
                            "removed": [],
                            "srid_changed": false,
                            "geometry_type_changed": false,
                            "primary_keys_changed": false,
                        },
                    },
                    "source_summary": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/data/source-summary/",
                    "import_started_at": "2025-05-19T23:30:16.585175Z",
                    "import_ended_at": "2025-05-19T23:30:29.110662Z",
                    "import_log": {
                        "invalid_geometries": 0,
                        "messages": 0,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/data/import-log/",
                    },
                    "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/",
                    "update_available": false,
                    "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/data/sample/",
                    "raster_resolution": null,
                    "empty_geometry_count": 6223,
                    "has_z": false,
                    "export_formats": [
                        {
                            "name": "DBF (dBase III)",
                            "mimetype": "application/x-zipped-shp",
                        },
                        {
                            "name": "MapInfo TAB",
                            "mimetype": "application/x-ogc-mapinfo_file",
                        },
                        {
                            "name": "MapInfo MIF",
                            "mimetype": "application/x-ogc-mapinfo_file+mif",
                        },
                        {"name": "CSV", "mimetype": "text/csv"},
                        {
                            "name": "GeoPackage / SQLite",
                            "mimetype": "application/x-ogc-gpkg",
                        },
                        {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
                    ],
                },
                "url_html": "https://data.linz.govt.nz/table/110593-suburb-locality-additional-name/",
                "url_canonical": "https://data.linz.govt.nz/table/110593-suburb-locality-additional-name/",
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/",
                "kind": "table",
                "categories": [
                    {
                        "name": "Suburbs and Localities",
                        "slug": "suburbs-and-localities",
                        "key": "suburbs-and-localities",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                        "ancestors": [],
                    }
                ],
                "tags": ["New Zealand"],
                "collected_at": null,
                "created_at": "2022-10-03T22:59:19.501397Z",
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": {
                    "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253862/metadata-resources/22223/",
                    "native": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/metadata/",
                    "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/metadata/iso/",
                    "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/metadata/dc/",
                },
                "elevation_field": "",
                "attachments": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/attachments/",
                "settings": {
                    "is_pinned": null,
                    "feedback_enabled": true,
                    "is_source_mirror": false,
                },
                "repository": {
                    "id": "p3VEme8",
                    "full_name": "linz/suburb-locality-additional-name",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-additional-name/",
                    "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-additional-name",
                    "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-additional-name",
                    "type": "repo",
                    "title": "Suburb Locality - Additional Name",
                    "first_published_at": "2023-08-09T02:22:14.553869Z",
                    "published_at": null,
                    "settings": {"feedback_enabled": true},
                    "user_capabilities": ["can-star", "can-clone"],
                    "user_permissions": ["find", "view", "download"],
                },
                "geotags": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/geotags/",
                "num_views": 652,
                "num_downloads": 419,
                "is_starred": false,
                "public_access": "download",
                "version": {
                    "id": 414040,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/tables/110593/versions/414040/",
                    "status": "ok",
                    "created_at": "2025-05-19T23:30:07.804642Z",
                    "reference": "",
                    "progress": 1.0,
                    "data_import": true,
                },
            },
            {
                "id": 113761,
                "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/",
                "type": "table",
                "title": "Suburb Locality - Population",
                "first_published_at": "2023-06-16T03:27:20.121434Z",
                "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/113761/422171/og.png",
                "published_at": "2025-05-19T23:31:26.869122Z",
                "featured_at": null,
                "services": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/",
                "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
                "user_permissions": ["find", "view", "download"],
                "description": "The Population data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). This table contains the population estimate for each suburb and locality, provided by StatsNZ.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
                "description_html": '<p>The Population data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. This table contains the population estimate for each suburb and locality, provided by StatsNZ.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
                "group": {
                    "id": 2174,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
                    "name": "Addressing",
                    "country": "NZ",
                    "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
                    "type": "normal",
                },
                "publisher": {
                    "id": "data.linz.govt.nz",
                    "name": "Land Information New Zealand",
                    "html_url": "https://data.linz.govt.nz/",
                    "slug_for_url": null,
                    "theme": {
                        "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                        "background_color": "004964",
                    },
                    "site": {
                        "url": "https://data.linz.govt.nz",
                        "name": "LINZ Data Service",
                    },
                    "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
                    "flags": {},
                    "description": null,
                },
                "data": {
                    "storage": "classic",
                    "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/datasources/",
                    "fields": [
                        {"name": "id", "type": "integer"},
                        {"name": "suburb_locality_id", "type": "integer"},
                        {"name": "population_estimate", "type": "integer"},
                    ],
                    "encoding": "utf-8",
                    "crs": null,
                    "primary_key_fields": ["id"],
                    "geometry_field": null,
                    "geometry_type": "",
                    "omitted_fields": [],
                    "tile_revision": 422171,
                    "feature_count": 3190,
                    "extent": null,
                    "datasource_count": 1,
                    "change_summary": {
                        "inserted": 0,
                        "updated": 0,
                        "deleted": 0,
                        "schema_changes": {
                            "added": [],
                            "changed": [],
                            "removed": [],
                            "srid_changed": false,
                            "geometry_type_changed": false,
                            "primary_keys_changed": false,
                        },
                    },
                    "source_summary": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/source-summary/",
                    "import_started_at": "2025-05-19T23:30:16.526945Z",
                    "import_ended_at": "2025-05-19T23:30:23.368693Z",
                    "import_log": {
                        "invalid_geometries": 0,
                        "messages": 0,
                        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/import-log/",
                    },
                    "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
                    "update_available": false,
                    "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/sample/",
                    "raster_resolution": null,
                    "empty_geometry_count": 3190,
                    "has_z": false,
                    "export_formats": [
                        {
                            "name": "DBF (dBase III)",
                            "mimetype": "application/x-zipped-shp",
                        },
                        {
                            "name": "MapInfo TAB",
                            "mimetype": "application/x-ogc-mapinfo_file",
                        },
                        {
                            "name": "MapInfo MIF",
                            "mimetype": "application/x-ogc-mapinfo_file+mif",
                        },
                        {"name": "CSV", "mimetype": "text/csv"},
                        {
                            "name": "GeoPackage / SQLite",
                            "mimetype": "application/x-ogc-gpkg",
                        },
                        {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
                    ],
                },
                "url_html": "https://data.linz.govt.nz/table/113761-suburb-locality-population/",
                "url_canonical": "https://data.linz.govt.nz/table/113761-suburb-locality-population/",
                "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
                "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
                "kind": "table",
                "categories": [
                    {
                        "name": "Suburbs and Localities",
                        "slug": "suburbs-and-localities",
                        "key": "suburbs-and-localities",
                        "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                        "ancestors": [],
                    }
                ],
                "tags": ["New Zealand"],
                "collected_at": null,
                "created_at": "2023-06-16T03:25:23.567953Z",
                "license": {
                    "id": 171,
                    "title": "Creative Commons Attribution 4.0 International",
                    "type": "cc-by",
                    "jurisdiction": "",
                    "version": "4.0",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
                    "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
                    "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
                },
                "metadata": {
                    "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253860/metadata-resources/22221/",
                    "native": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/",
                    "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/iso/",
                    "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/dc/",
                },
                "elevation_field": "",
                "attachments": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/attachments/",
                "settings": {
                    "is_pinned": null,
                    "feedback_enabled": true,
                    "is_source_mirror": false,
                },
                "repository": {
                    "id": "Y3N4Bwq",
                    "full_name": "linz/suburb-locality-population",
                    "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-population/",
                    "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-population",
                    "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-population",
                    "type": "repo",
                    "title": "Suburb Locality - Population",
                    "first_published_at": "2023-08-08T19:30:25.028943Z",
                    "published_at": null,
                    "settings": {"feedback_enabled": true},
                    "user_capabilities": ["can-star", "can-clone"],
                    "user_permissions": ["find", "view", "download"],
                },
                "geotags": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/geotags/",
                "num_views": 2976,
                "num_downloads": 515,
                "is_starred": false,
                "public_access": "download",
                "version": {
                    "id": 414039,
                    "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
                    "status": "ok",
                    "created_at": "2025-05-19T23:30:04.023695Z",
                    "reference": "",
                    "progress": 1.0,
                    "data_import": true,
                },
            },
        ],
        "version": {
            "id": 2190,
            "url": "https://data.linz.govt.nz/services/api/v1.x/sets/7364/versions/2190/",
            "created_at": "2023-06-20T03:25:52.069745Z",
        },
    },
}
