table = {
    request: "https://data.linz.govt.nz/services/api/v1.x/tables/113761/",
    response: {
        "id": 113761,
        "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/",
        "type": "table",
        "title": "Suburb Locality - Population",
        "first_published_at": "2023-06-16T03:27:20.121434Z",
        "thumbnail_url": "https://assets.koordinates.com/kx-dandelion-live2-public/thumbs/layers/113761/422171/og.png",
        "published_at": "2025-05-19T23:31:26.869122Z",
        "featured_at": null,
        "services": [
            {
                "id": "s3V8qtdtS47dQxd",
                "authority": "kart",
                "key": "kart",
                "short_name": "Kart",
                "label": "Kart Repository",
                "auth_method": [],
                "auth_scopes": [],
                "domain": "data.linz.govt.nz",
                "template_urls": [
                    {
                        "name": "SSH Clone Location",
                        "service_url": "kart@data.koordinates.com:linz/suburb-locality-population",
                    },
                    {
                        "name": "HTTPS Clone Location",
                        "service_url": "https://data.koordinates.com/linz/suburb-locality-population",
                    },
                ],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/s3V8qtdtS47dQxd/permissions/",
                "advertised": true,
                "user_capabilities": [],
                "enabled": true,
            },
            {
                "id": "s3VH25C1cmPN6Xy",
                "authority": "koordinates",
                "key": "data-table",
                "short_name": "Data Table API",
                "label": "Data table API for feature and raster-tile queries",
                "auth_method": ["apikey"],
                "auth_scopes": ["query"],
                "domain": "data.linz.govt.nz",
                "template_urls": [],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/s3VH25C1cmPN6Xy/permissions/",
                "advertised": false,
                "user_capabilities": [],
                "enabled": true,
            },
            {
                "id": "s3V8qtdtS3yJDpY",
                "authority": "ogc",
                "key": "wfs",
                "short_name": "WFS",
                "label": "OGC Web Feature Service",
                "auth_method": ["apikey"],
                "auth_scopes": ["wxs:wfs"],
                "domain": "data.linz.govt.nz",
                "template_urls": [
                    {
                        "name": "Layer WFS Capabilities",
                        "service_url": "https://data.linz.govt.nz/services;key=[api_token]/wfs/table-113761/?service=WFS&request=GetCapabilities",
                    },
                    {
                        "name": "All WFS Capabilities",
                        "service_url": "https://data.linz.govt.nz/services;key=[api_token]/wfs/?service=WFS&request=GetCapabilities",
                    },
                ],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/s3V8qtdtS3yJDpY/permissions/",
                "advertised": true,
                "user_capabilities": [],
                "enabled": true,
            },
            {
                "id": "s3V8qtdtS3zBv65",
                "authority": "koordinates",
                "key": "wfs-changesets",
                "short_name": "WFS Changesets",
                "label": "Retrieve data changesets via WFS",
                "auth_method": ["apikey"],
                "auth_scopes": ["wxs:wfs"],
                "domain": "data.linz.govt.nz",
                "template_urls": [
                    {
                        "name": "WFS Changesets",
                        "service_url": "https://data.linz.govt.nz/services;key=[api_token]/wfs/table-113761?service=WFS&version=2.0.0&request=GetFeature&TypeName=table-113761-changeset&OutputFormat=[output_format]&sortBy=[sort_by]&viewparams=from:[start_time];to:[end_time]",
                    }
                ],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/s3V8qtdtS3zBv65/permissions/",
                "advertised": true,
                "user_capabilities": [],
                "enabled": true,
            },
            {
                "id": "s3V8qtdtS3wz5nY",
                "authority": "ogc",
                "key": "csw",
                "short_name": "CS-W",
                "label": "Catalog Service for the Web",
                "auth_method": [],
                "auth_scopes": [],
                "domain": "data.linz.govt.nz",
                "template_urls": [
                    {
                        "name": "Web Catalog Services",
                        "service_url": "https://data.linz.govt.nz/services/csw/?service=CSW&amp;request=GetCapabilities",
                    }
                ],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/s3V8qtdtS3wz5nY/permissions/",
                "advertised": true,
                "user_capabilities": [],
                "enabled": true,
            },
            {
                "id": "s3VH25C1cmTQbDK",
                "authority": "koordinates",
                "key": "export",
                "short_name": "Export",
                "label": "Export Service",
                "auth_method": [],
                "auth_scopes": [],
                "domain": "data.linz.govt.nz",
                "template_urls": [],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/s3VH25C1cmTQbDK/permissions/",
                "advertised": false,
                "user_capabilities": [],
                "enabled": true,
            },
            {
                "id": "s3VH25C1cmTStzq",
                "authority": "koordinates",
                "key": "data-table-ui",
                "short_name": "Data Table UI",
                "auth_method": [],
                "auth_scopes": [],
                "domain": "data.linz.govt.nz",
                "template_urls": [],
                "capabilities": [],
                "permissions": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/services/s3VH25C1cmTStzq/permissions/",
                "advertised": false,
                "user_capabilities": [],
                "enabled": true,
            },
        ],
        "user_capabilities": ["can-star", "can-export", "can-view-data-table"],
        "user_permissions": ["find", "view", "download"],
        "description": "The Population data table is part of [NZ Suburbs and Localities Dataset](https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/). This table contains the population estimate for each suburb and locality, provided by StatsNZ.\n\n---\n\n[NZ Suburbs and Localities](https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/) is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.\n\nThe suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.\n\nEach suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. \n\nFor more information please refer to the NZ Suburbs and Localities Guidance documents:\n\n[Data Dictionary](https://data.linz.govt.nz/document/24593/)\n[Change Request Process](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\n[Change Request Principles, Requirements and Rules](https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data)\nChanges to NZ Suburbs and Localities can be requested by emailing [addresses@linz.govt.nz](mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request)",
        "description_html": '<p>The Population data table is part of <a href="https://data.linz.govt.nz/set/7364-nz-suburbs-and-localities-dataset/">NZ Suburbs and Localities Dataset</a>. This table contains the population estimate for each suburb and locality, provided by StatsNZ.</p>\n<hr>\n<p><a href="https://data.linz.govt.nz/layer/113764-nz-suburbs-and-localities/">NZ Suburbs and Localities</a> is an easy to use layer generated from the normalised NZ Suburbs and Localities Dataset. It describes the spatial extent and name of communities in urban areas (suburbs) and rural areas (localities) for navigation and location purposes.</p>\n<p>The suburb and locality boundaries cover New Zealand including North Island, South Island, Stewart Island/Rakiura, Chatham Islands, and nearby offshore islands.</p>\n<p>Each suburb and locality is assigned a name, major name, Territorial Authority and, if appropriate, additional in use names.  A population estimate is provided for each suburb and locality by Stats NZ. </p>\n<p>For more information please refer to the NZ Suburbs and Localities Guidance documents:</p>\n<p><a href="https://data.linz.govt.nz/document/24593/">Data Dictionary</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Process</a><br>\n<a href="https://www.linz.govt.nz/products-services/data/types-linz-data/suburbs-and-localities-data">Change Request Principles, Requirements and Rules</a><br>\nChanges to NZ Suburbs and Localities can be requested by emailing <a href="mailto:addresses@linz.govt.nz?subject=NZ Suburbs and Localities Change Request">addresses@linz.govt.nz</a></p>',
        "group": {
            "id": 2174,
            "url": "https://data.linz.govt.nz/services/api/v1.x/groups/2174/",
            "name": "Addressing",
            "country": "NZ",
            "org": "https://data.linz.govt.nz/services/api/v1.x/orgs/o3MzyVCb7p6JYVb/",
            "type": "normal",
        },
        "publisher": {
            "id": "data.linz.govt.nz",
            "name": "Land Information New Zealand",
            "html_url": "https://data.linz.govt.nz/",
            "slug_for_url": null,
            "theme": {
                "logo": "https://assets.koordinates.com/kx-dandelion-live2-public/settings/branding/linz.png",
                "background_color": "004964",
            },
            "site": {"url": "https://data.linz.govt.nz", "name": "LINZ Data Service"},
            "url": "https://data.linz.govt.nz/services/api/v1.x/publishers/data.linz.govt.nz/",
            "flags": {},
            "description": null,
        },
        "data": {
            "storage": "classic",
            "datasources": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/datasources/",
            "fields": [
                {"name": "id", "type": "integer"},
                {"name": "suburb_locality_id", "type": "integer"},
                {"name": "population_estimate", "type": "integer"},
            ],
            "encoding": "utf-8",
            "crs": null,
            "primary_key_fields": ["id"],
            "geometry_field": null,
            "geometry_type": "",
            "omitted_fields": [],
            "tile_revision": 422171,
            "feature_count": 3190,
            "extent": null,
            "datasource_count": 1,
            "change_summary": {
                "inserted": 0,
                "updated": 0,
                "deleted": 0,
                "schema_changes": {
                    "added": [],
                    "changed": [],
                    "removed": [],
                    "srid_changed": false,
                    "geometry_type_changed": false,
                    "primary_keys_changed": false,
                },
            },
            "source_summary": {"formats": ["SQLite"], "types": ["CIFS"]},
            "import_started_at": "2025-05-19T23:30:16.526945Z",
            "import_ended_at": "2025-05-19T23:30:23.368693Z",
            "import_log": {
                "invalid_geometries": 0,
                "messages": 0,
                "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/import-log/",
            },
            "import_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
            "update_available": false,
            "sample": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/data/sample/",
            "raster_resolution": null,
            "empty_geometry_count": 3190,
            "has_z": false,
            "export_formats": [
                {"name": "DBF (dBase III)", "mimetype": "application/x-zipped-shp"},
                {"name": "MapInfo TAB", "mimetype": "application/x-ogc-mapinfo_file"},
                {
                    "name": "MapInfo MIF",
                    "mimetype": "application/x-ogc-mapinfo_file+mif",
                },
                {"name": "CSV", "mimetype": "text/csv"},
                {"name": "GeoPackage / SQLite", "mimetype": "application/x-ogc-gpkg"},
                {"name": "Geodatabase", "mimetype": "applicaton/x-ogc-filegdb"},
            ],
        },
        "url_html": "https://data.linz.govt.nz/table/113761-suburb-locality-population/",
        "url_canonical": "https://data.linz.govt.nz/table/113761-suburb-locality-population/",
        "published_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
        "this_version": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
        "kind": "table",
        "categories": [
            {
                "name": "Suburbs and Localities",
                "slug": "suburbs-and-localities",
                "key": "suburbs-and-localities",
                "url": "https://data.linz.govt.nz/services/api/v1.x/categories/suburbs-and-localities/",
                "ancestors": [],
            }
        ],
        "tags": ["New Zealand"],
        "collected_at": null,
        "created_at": "2023-06-16T03:25:23.567953Z",
        "license": {
            "id": 171,
            "title": "Creative Commons Attribution 4.0 International",
            "type": "cc-by",
            "jurisdiction": "",
            "version": "4.0",
            "url": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/",
            "url_html": "https://data.linz.govt.nz/license/attribution-4-0-international/",
            "url_fulltext": "https://data.linz.govt.nz/services/api/v1.x/licenses/171/fulltext/",
        },
        "metadata": {
            "resource": "https://data.linz.govt.nz/services/api/v1.x/sources/253860/metadata-resources/22221/",
            "native": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/",
            "iso": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/iso/",
            "dc": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/metadata/dc/",
        },
        "elevation_field": "",
        "attachments": [],
        "settings": {
            "is_pinned": null,
            "feedback_enabled": true,
            "is_source_mirror": false,
        },
        "repository": {
            "id": "Y3N4Bwq",
            "full_name": "linz/suburb-locality-population",
            "url": "https://data.linz.govt.nz/services/api/v1.x/repos/linz/suburb-locality-population/",
            "clone_location_ssh": "kart@data.koordinates.com:linz/suburb-locality-population",
            "clone_location_https": "https://data.koordinates.com/linz/suburb-locality-population",
            "type": "repo",
            "title": "Suburb Locality - Population",
            "first_published_at": "2023-08-08T19:30:25.028943Z",
            "published_at": null,
            "settings": {"feedback_enabled": true},
            "user_capabilities": ["can-star", "can-clone"],
            "user_permissions": ["find", "view", "download"],
        },
        "geotags": [],
        "num_views": 2976,
        "num_downloads": 515,
        "is_starred": false,
        "public_access": "download",
        "version": {
            "id": 414039,
            "url": "https://data.linz.govt.nz/services/api/v1.x/tables/113761/versions/414039/",
            "status": "ok",
            "created_at": "2025-05-19T23:30:04.023695Z",
            "reference": "",
            "progress": 1.0,
            "data_import": true,
        },
    },
}
