authentication:
  section: linz 
  username: kapipy_example

audit_folder: C:/temp/data/tcdc

# Anything in the default section will be added to each layer
# but will be overridden if also specified by any layer.
defaults:  
  crop_layer_id: 3036
  crop_feature_id: 10870 #Thames-Coromandel District Council
  target_db: C:/temp/data/tcdc/linz_tcdc.gdb
  out_sr: 2193

layers:
  - id: 50787
    target_fc: NZ_Geodetic_Marks

  - id: 50772
    target_fc: NZ_Primary_Parcels

  - id: 50329
    target_fc: NZ_Road_Centrelines_Topo_50k

